spring:
  application:
    name: user-service

  zipkin:
    enabled: true
    sender:
      type: web
    # zipkkin dashboard的地址：通过真实IP地址访问
    baseUrl: http://42.123.99.25:9411/
    # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，本版本(spring-cloud-sleuth-core-1.2.5.RELEASE)不支持，需要从spring-cloud-sleuth-core-1.3.0.RELEASE开始支持这个功能
    # 配置如下：
    # baseUrl: http://cloud-dashboard-zipkin/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      #  默认值为0.1f，现在为了测试设置100%采集
      probability: 1

server:
  port: 8711

eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      #eureka高可用时,将自己注册到其它eureka服务上
      defaultZone: http://42.123.99.25:8701/eureka,http://42.123.99.25:8702/eureka,http://42.123.99.25:8703/eureka