spring:
  application:
    name: user-service

server:
  port: 8711

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      #eureka高可用时,将自己注册到其它eureka服务上
      defaultZone: http://42.123.99.25:8701/eureka,http://42.123.99.25:8702/eureka,http://42.123.99.25:8703/eureka