spring:
  application:
    name: eureka-server

---
spring:
  profiles: peer1

server:
  port: 8701

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      #eureka高可用时,将自己注册到其它eureka服务上
      defaultZone: http://localhost:8702/eureka,http://localhost:8703/eureka


---
spring:
  profiles: peer2

server:
  port: 8702

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka,http://localhost:8703/eureka

---
spring:
  profiles: peer3

server:
  port: 8703

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka,http://localhost:8702/eureka