spring:
  application:
    name: eureka-server

---
spring:
  profiles: peer1

server:
  port: 8701

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      #eureka高可用时,将自己注册到其它eureka服务上
      defaultZone: http://eureka2:8702/eureka,http://eureka3:8703/eureka


---
spring:
  profiles: peer2

server:
  port: 8702

eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8701/eureka,http://eureka3:8703/eureka

---
spring:
  profiles: peer3

server:
  port: 8703

eureka:
  instance:
    hostname: eureka3
  client:
    serviceUrl:
      defaultZone: http://eureka1:8701/eureka,http://eureka2:8702/eureka